/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "C:\\Program Files\\nodejs\\node_modules\\vuepress\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-9409de3a",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-9409de3a").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-4e4a5718",
    path: "/router/base/test1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4e4a5718").then(next)
    },
  },
  {
    name: "v-ed5f7f10",
    path: "/router/base/test2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-ed5f7f10").then(next)
    },
  },
  {
    name: "v-0147d990",
    path: "/router/base/test4.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0147d990").then(next)
    },
  },
  {
    name: "v-7753ac50",
    path: "/router/base/test3.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7753ac50").then(next)
    },
  },
  {
    name: "v-75859c66",
    path: "/router/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-75859c66").then(next)
    },
  },
  {
    path: "/router/index.html",
    redirect: "/router/"
  },
  {
    name: "v-1809403c",
    path: "/router/other/axios.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1809403c").then(next)
    },
  },
  {
    name: "v-6a841b52",
    path: "/router/other/mock.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6a841b52").then(next)
    },
  },
  {
    name: "v-7997d190",
    path: "/router/react-native/advance.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7997d190").then(next)
    },
  },
  {
    name: "v-2ae93650",
    path: "/router/react-native/react-navigation.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2ae93650").then(next)
    },
  },
  {
    name: "v-70766572",
    path: "/router/myComponent/ui.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-70766572").then(next)
    },
  },
  {
    name: "v-6cc0e312",
    path: "/router/react/keng.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6cc0e312").then(next)
    },
  },
  {
    name: "v-6ec65cc6",
    path: "/router/react/advance.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6ec65cc6").then(next)
    },
  },
  {
    name: "v-e0290490",
    path: "/router/self/verify.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-e0290490").then(next)
    },
  },
  {
    name: "v-ab1fcf50",
    path: "/router/self/cache.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-ab1fcf50").then(next)
    },
  },
  {
    name: "v-3f6deb92",
    path: "/router/react/react-router.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3f6deb92").then(next)
    },
  },
  {
    name: "v-56b975b6",
    path: "/router/react-native/keng.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-56b975b6").then(next)
    },
  },
  {
    name: "v-5e545c7e",
    path: "/router/react/react-redux.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5e545c7e").then(next)
    },
  },
  {
    name: "v-68989908",
    path: "/router/self/vuex-keep-data.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-68989908").then(next)
    },
  },
  {
    name: "v-73bf3db8",
    path: "/router/ts/advance.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-73bf3db8").then(next)
    },
  },
  {
    name: "v-0b92bf10",
    path: "/router/vue/advance.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0b92bf10").then(next)
    },
  },
  {
    name: "v-77628990",
    path: "/router/ts/vue.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-77628990").then(next)
    },
  },
  {
    name: "v-6f3147d8",
    path: "/router/ts/react.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6f3147d8").then(next)
    },
  },
  {
    name: "v-43224682",
    path: "/router/vue/component.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-43224682").then(next)
    },
  },
  {
    name: "v-8e2fbe9c",
    path: "/router/vue/keng.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-8e2fbe9c").then(next)
    },
  },
  {
    name: "v-b6dddadc",
    path: "/router/vue/vue-router.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-b6dddadc").then(next)
    },
  },
  {
    name: "v-52c53d9c",
    path: "/router/webpack/vue-cli3.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-52c53d9c").then(next)
    },
  },
  {
    name: "v-0c67f69c",
    path: "/router/vue/vue3.0.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0c67f69c").then(next)
    },
  },
  {
    name: "v-6f0e079c",
    path: "/router/webpack/create-react-app.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6f0e079c").then(next)
    },
  },
  {
    name: "v-7b738f12",
    path: "/router/vue/vuex.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7b738f12").then(next)
    },
  },
  {
    path: '*',
    component: GlobalLayout
  }
]