/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "C:\\Program Files\\nodejs\\node_modules\\vuepress\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-75859c66",
    path: "/router/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-75859c66").then(next)
    },
  },
  {
    path: "/router/index.html",
    redirect: "/router/"
  },
  {
    name: "v-4e4a5718",
    path: "/router/base/test1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4e4a5718").then(next)
    },
  },
  {
    name: "v-ed5f7f10",
    path: "/router/base/test2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-ed5f7f10").then(next)
    },
  },
  {
    name: "v-7753ac50",
    path: "/router/base/test3.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7753ac50").then(next)
    },
  },
  {
    name: "v-9409de3a",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-9409de3a").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-0147d990",
    path: "/router/base/test4.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0147d990").then(next)
    },
  },
  {
    name: "v-6a841b52",
    path: "/router/other/mock.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6a841b52").then(next)
    },
  },
  {
    name: "v-6ec65cc6",
    path: "/router/react/advance.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6ec65cc6").then(next)
    },
  },
  {
    name: "v-6cc0e312",
    path: "/router/react/keng.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6cc0e312").then(next)
    },
  },
  {
    name: "v-3f6deb92",
    path: "/router/react/react-router.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3f6deb92").then(next)
    },
  },
  {
    name: "v-d206563c",
    path: "/router/react/redux.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-d206563c").then(next)
    },
  },
  {
    name: "v-14857750",
    path: "/router/vue/axios.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-14857750").then(next)
    },
  },
  {
    name: "v-8e2fbe9c",
    path: "/router/vue/keng.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-8e2fbe9c").then(next)
    },
  },
  {
    name: "v-b6dddadc",
    path: "/router/vue/vue-router.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-b6dddadc").then(next)
    },
  },
  {
    name: "v-0b92bf10",
    path: "/router/vue/advance.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0b92bf10").then(next)
    },
  },
  {
    name: "v-7b738f12",
    path: "/router/vue/vuex.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7b738f12").then(next)
    },
  },
  {
    path: '*',
    component: GlobalLayout
  }
]