/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "李皮皮技术博客",
  "description": "我的程序永远不会有bug，那些只是开发出来的随机的功能特征",
  "base": "/blog/",
  "headTags": [],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": "true,",
        "heroImage": "/logo.jpg",
        "actionText": "前往 →",
        "actionLink": "/router/",
        "features": [
          {
            "title": "vue的进阶技能",
            "details": "vue的学习笔记、vue进阶技能在业务应用及其源码分析"
          },
          {
            "title": "react的进阶技能",
            "details": "react的学习笔记、react进阶技能在业务应用及其源码分析"
          },
          {
            "title": "typescript的使用",
            "details": "typescript的使用、ts在vue和react的使用"
          },
          {
            "title": "构建工具的使用",
            "details": "webpack、gulp常用api配置"
          },
          {
            "title": "react-native的学习笔记",
            "details": "从零开始的react-native的学习笔记"
          },
          {
            "title": "egg.js、mySql的学习笔记",
            "details": "从零开始的egg.js、mySql的学习笔记"
          },
          {
            "title": "vue、react组件的业务轮子",
            "details": "包含的vue和react的通用性组件、业务组件等等"
          },
          {
            "title": "知识库",
            "details": "一些干货和node、vue、react、react-native库的集合"
          },
          {
            "title": "其他",
            "details": "http、面试、其他语言等等知识"
          }
        ]
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-e6a9a73c",
      "path": "/"
    },
    {
      "title": "介绍",
      "frontmatter": {},
      "regularPath": "/router/",
      "relativePath": "router/README.md",
      "key": "v-df77a4b6",
      "path": "/router/"
    },
    {
      "title": "测试案例1",
      "frontmatter": {},
      "regularPath": "/router/base/test1.html",
      "relativePath": "router/base/test1.md",
      "key": "v-8be8310e",
      "path": "/router/base/test1.html"
    },
    {
      "title": "测试案例2",
      "frontmatter": {},
      "regularPath": "/router/base/test2.html",
      "relativePath": "router/base/test2.md",
      "key": "v-15dc5e4e",
      "path": "/router/base/test2.html"
    },
    {
      "title": "测试案例3",
      "frontmatter": {},
      "regularPath": "/router/base/test3.html",
      "relativePath": "router/base/test3.md",
      "key": "v-3017ba39",
      "path": "/router/base/test3.html"
    },
    {
      "title": "测试案例4",
      "frontmatter": {},
      "regularPath": "/router/base/test4.html",
      "relativePath": "router/base/test4.md",
      "key": "v-6b1da399",
      "path": "/router/base/test4.html"
    },
    {
      "title": "mock 教程",
      "frontmatter": {},
      "regularPath": "/router/other/mock.html",
      "relativePath": "router/other/mock.md",
      "key": "v-5374a89a",
      "path": "/router/other/mock.html",
      "headers": [
        {
          "level": 3,
          "title": "vue-cli3 搭建的 mock",
          "slug": "vue-cli3-搭建的-mock"
        }
      ]
    },
    {
      "title": "进阶技能",
      "frontmatter": {},
      "regularPath": "/router/react-native/advance.html",
      "relativePath": "router/react-native/advance.md",
      "key": "v-d6faa5ce",
      "path": "/router/react-native/advance.html",
      "headers": [
        {
          "level": 3,
          "title": "react-native 的进阶技能的使用及在业务中的应用",
          "slug": "react-native-的进阶技能的使用及在业务中的应用"
        }
      ]
    },
    {
      "title": "一些 react 上的坑总结",
      "frontmatter": {},
      "regularPath": "/router/react-native/keng.html",
      "relativePath": "router/react-native/keng.md",
      "key": "v-14a24857",
      "path": "/router/react-native/keng.html"
    },
    {
      "title": "react-navigation",
      "frontmatter": {},
      "regularPath": "/router/react-native/react-navigation.html",
      "relativePath": "router/react-native/react-navigation.md",
      "key": "v-31fea479",
      "path": "/router/react-native/react-navigation.html",
      "headers": [
        {
          "level": 3,
          "title": "react-navigation 常用的 api 及其在业务中的小技巧",
          "slug": "react-navigation-常用的-api-及其在业务中的小技巧"
        }
      ]
    },
    {
      "title": "一些 react 上的坑总结",
      "frontmatter": {},
      "regularPath": "/router/react/keng.html",
      "relativePath": "router/react/keng.md",
      "key": "v-4efb191a",
      "path": "/router/react/keng.html"
    },
    {
      "title": "进阶技能",
      "frontmatter": {},
      "regularPath": "/router/react/advance.html",
      "relativePath": "router/react/advance.md",
      "key": "v-5b4f3f32",
      "path": "/router/react/advance.html",
      "headers": [
        {
          "level": 3,
          "title": "vue 的进阶技能的使用及在业务中的应用",
          "slug": "vue-的进阶技能的使用及在业务中的应用"
        }
      ]
    },
    {
      "title": "redux",
      "frontmatter": {},
      "regularPath": "/router/react/react-redux.html",
      "relativePath": "router/react/react-redux.md",
      "key": "v-1c3d2f1f",
      "path": "/router/react/react-redux.html"
    },
    {
      "title": "react-router",
      "frontmatter": {},
      "regularPath": "/router/react/react-router.html",
      "relativePath": "router/react/react-router.md",
      "key": "v-266c99f3",
      "path": "/router/react/react-router.html",
      "headers": [
        {
          "level": 3,
          "title": "react-router 常用的 api 及其在业务中的小技巧",
          "slug": "react-router-常用的-api-及其在业务中的小技巧"
        }
      ]
    },
    {
      "title": "axios",
      "frontmatter": {},
      "regularPath": "/router/vue/axios.html",
      "relativePath": "router/vue/axios.md",
      "key": "v-0e81abf1",
      "path": "/router/vue/axios.html"
    },
    {
      "title": "vue-router",
      "frontmatter": {},
      "regularPath": "/router/vue/vue-router.html",
      "relativePath": "router/vue/vue-router.md",
      "key": "v-6bb0b1f3",
      "path": "/router/vue/vue-router.html",
      "headers": [
        {
          "level": 3,
          "title": "vue-router 常用的 api 及其在业务中的小技巧",
          "slug": "vue-router-常用的-api-及其在业务中的小技巧"
        }
      ]
    },
    {
      "title": "一些 vue 上的坑总结",
      "frontmatter": {},
      "regularPath": "/router/vue/keng.html",
      "relativePath": "router/vue/keng.md",
      "key": "v-2bfb0993",
      "path": "/router/vue/keng.html"
    },
    {
      "title": "vuex",
      "frontmatter": {},
      "regularPath": "/router/vue/vuex.html",
      "relativePath": "router/vue/vuex.md",
      "key": "v-22f3101a",
      "path": "/router/vue/vuex.html"
    },
    {
      "title": "进阶技能",
      "frontmatter": {},
      "regularPath": "/router/vue/advance.html",
      "relativePath": "router/vue/advance.md",
      "key": "v-7bd59c99",
      "path": "/router/vue/advance.html",
      "headers": [
        {
          "level": 3,
          "title": "vue 的进阶技能的使用及在业务中的应用",
          "slug": "vue-的进阶技能的使用及在业务中的应用"
        },
        {
          "level": 3,
          "title": "api 应用系列",
          "slug": "api-应用系列"
        },
        {
          "level": 3,
          "title": "优化系列",
          "slug": "优化系列"
        }
      ]
    }
  ],
  "themeConfig": {
    "nav": [
      {
        "text": "主页",
        "link": "/"
      },
      {
        "text": "了解更多",
        "link": "/router/"
      },
      {
        "text": "知识库",
        "link": "/knowledge/"
      },
      {
        "text": "github",
        "items": [
          {
            "text": "focus-outside",
            "link": "https://github.com/TaoXuSheng/focus-outside"
          },
          {
            "text": "stylus-converter",
            "link": "https://github.com/TaoXuSheng/stylus-converter"
          }
        ]
      }
    ],
    "sidebar": {
      "/router/": [
        {
          "title": "vue",
          "collapsable": true,
          "children": [
            {
              "title": "vue进阶技能",
              "collapsable": true,
              "children": [
                "vue/advance"
              ]
            },
            {
              "title": "vue全家桶进阶使用及源码",
              "collapsable": true,
              "children": [
                "vue/vue-router",
                "vue/vuex",
                "vue/axios"
              ]
            },
            {
              "title": "vue组件",
              "collapsable": true,
              "children": []
            },
            "vue/keng"
          ]
        },
        {
          "title": "react",
          "collapsable": true,
          "children": [
            {
              "title": "reac进阶技能",
              "collapsable": true,
              "children": [
                "react/advance"
              ]
            },
            {
              "title": "react其生态库的使用",
              "collapsable": true,
              "children": [
                "react/react-router",
                "react/react-redux"
              ]
            },
            {
              "title": "react组件",
              "collapsable": true,
              "children": []
            },
            "react/keng"
          ]
        },
        {
          "title": "react-native",
          "collapsable": true,
          "children": [
            {
              "title": "react-native",
              "collapsable": true,
              "children": [
                "react-native/advance"
              ]
            },
            {
              "title": "react其生态库的使用",
              "collapsable": true,
              "children": [
                "react-native/react-navigation"
              ]
            },
            {
              "title": "react组件",
              "collapsable": true,
              "children": []
            },
            "react/keng"
          ]
        },
        {
          "title": "工具类组件",
          "collapsable": true,
          "children": []
        },
        {
          "title": "其他知识",
          "collapsable": true,
          "children": [
            "other/mock"
          ]
        }
      ],
      "/knowledge/": [
        {
          "title": "CSS知识库",
          "collapsable": false,
          "children": []
        },
        {
          "title": "JS知识库",
          "collapsable": false,
          "children": []
        },
        {
          "title": "node知识库",
          "collapsable": false,
          "children": []
        },
        {
          "title": "vue知识库",
          "collapsable": false,
          "children": []
        }
      ]
    }
  }
}